name: Deploy to staging

on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: SSH into server and deploy
        run: |
          # Save the private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          # Add the server to known_hosts to avoid host verification errors
          mkdir -p ~/.ssh
          ssh-keyscan -H 64.227.147.124 >> ~/.ssh/known_hosts

          # SSH and deploy
          ssh -i ~/ssh_key root@64.227.147.124 << 'EOF'
            cd week-25-ci-next-app/
            git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
