name: Deploy to staging

on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: SSH into server and deploy
        run: |
          # this echo command takes the key and add it to the file name agter &>
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          # SSH and run all deployment commands
          ssh -i ~/ssh_key root@64.227.147.124 << 'EOF'
            echo "Pulling latest code..."
            cd week-25-ci-next-app/
            git pull

            echo "Installing dependencies..."
            pnpm install

            echo "Building project..."
            pnpm run build

            echo "Restarting servers..."
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
