name: Deploy to staging

on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Save SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 600 ~/ssh_key

      - name: SSH and deploy everything
        run: |
          ssh -i ~/ssh_key root@64.227.147.124 << 'EOF'
            echo "Step 1: Pull latest code"
            cd week-25-ci-next-app/
            git pull

            echo "Step 2: Install dependencies"
            pnpm install

            echo "Step 3: Build project"
            pnpm run build

            echo "Step 4: Restart servers"
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
